on:
  push:
    branches: [master, release-*]
    tags: ["*.*.*"]
  pull_request:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    name: windows-2019
    runs-on: windows-2019
    steps:
      - uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439
        with:
          dotnet-version: "3.1.402"
      - run: dotnet --info
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          fetch-depth: 0
      - run: ./build.cmd
      - run: 'forfiles /m *.nupkg /s /c "cmd /c echo %~nx0: Pushing @path && dotnet nuget push @path --source https://www.myget.org/F/adamralph-ci/api/v2/package --api-key ${{ secrets.MYGET_ADAMRALPH_CI_API_KEY }}"'
