on:
  push:
    branches:
    - master
    - release-*
    tags:
    - '*.*.*'
  pull_request:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439
      with:
        dotnet-version: '3.1.402'
    - run: dotnet --info
    - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
    - if: contains(matrix.os, 'windows')
      run: ./build.cmd
    - if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
      run: ./build.sh
    - if: matrix.os == 'windows-2019'
      run: 'forfiles /m *.nupkg /s /c "cmd /c echo %~nx0: Pushing @path && dotnet nuget push @path --source https://www.myget.org/F/adamralph-ci/api/v2/package --api-key ${{ secrets.MYGET_ADAMRALPH_CI_API_KEY }}"'
