on:
  push:
    branches: [master, release-*]
    tags: ["*.*.*"]
  pull_request:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    name: windows-2019
    runs-on: windows-2019
    steps:
      - name: setup-dotnet 2.1.811
        uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439
        with:
          dotnet-version: "2.1.811"
      - name: setup-dotnet 3.1.404
        uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439
        with:
          dotnet-version: "3.1.404"
      - name: setup-dotnet 5.0.100
        uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439
        with:
          dotnet-version: "5.0.100"
      - run: dotnet --info
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          fetch-depth: 0
      - run: ./build.cmd
      - run: dotnet nuget push **/*.nupkg --source https://www.myget.org/F/adamralph-ci/api/v2/package --api-key ${{ secrets.MYGET_ADAMRALPH_CI_API_KEY }}
